const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d', { alpha: false });
ctx.imageSmoothingEnabled = false;

const UI = {
  loading: document.getElementById('loading'), loadingBar: document.getElementById('loading-bar'),
  title: document.getElementById('title-screen'), how: document.getElementById('how-screen'),
  dialogue: document.getElementById('dialogue'), portrait: document.getElementById('portrait'),
  speaker: document.getElementById('speaker'), dialogueText: document.getElementById('dialogue-text'),
  pause: document.getElementById('pause-screen'), result: document.getElementById('result-screen'),
  resultKicker: document.getElementById('result-kicker'), resultTitle: document.getElementById('result-title'),
  resultText: document.getElementById('result-text'), resultStats: document.getElementById('result-stats'),
  resultBtn: document.getElementById('result-btn'), toast: document.getElementById('toast'),
  continueBtn: document.getElementById('continue-btn'),
};

const W = canvas.width, H = canvas.height, FLOOR_Y = 622, GRAVITY = 1800;
const keys = new Set(), pressed = new Set(), touchState = new Set();
const clamp = (n,a,b)=>Math.max(a,Math.min(b,n));
const lerp = (a,b,t)=>a+(b-a)*t;
const rand = (a,b)=>a+Math.random()*(b-a);
const chance = p=>Math.random()<p;
const rectsOverlap = (a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const palette={ember:'#ff5a32',gold:'#ffe1a0',divine:'#f5d875',divine2:'#fff4c2',hp:'#d54343',mp:'#3cb7ce',ult:'#e8b84f'};

class AudioBus{
  constructor(){this.ac=null;this.enabled=true;}
  ensure(){if(!this.ac)this.ac=new(window.AudioContext||window.webkitAudioContext)();if(this.ac.state==='suspended')this.ac.resume();}
  tone(freq=220,duration=.08,type='square',volume=.035,slide=0){if(!this.enabled)return;this.ensure();const t=this.ac.currentTime,o=this.ac.createOscillator(),g=this.ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),t+duration);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(this.ac.destination);o.start(t);o.stop(t+duration);}
  hit(strong=false){this.tone(strong?95:145,strong?.16:.08,'sawtooth',strong?.06:.035,strong?-40:-18);}
  jump(){this.tone(220,.12,'square',.025,160);} dash(){this.tone(540,.09,'sawtooth',.025,-260);}
  skill(){this.tone(180,.22,'triangle',.045,620);} ult(){this.tone(90,.65,'sawtooth',.06,720);setTimeout(()=>this.tone(880,.35,'square',.035,-300),180);}
  pickup(){this.tone(520,.12,'triangle',.03,280);} hurt(){this.tone(120,.18,'square',.05,-50);}
}
const audio=new AudioBus();

class Particle{
  constructor(x,y,o={}){this.x=x;this.y=y;this.vx=o.vx??rand(-110,110);this.vy=o.vy??rand(-180,-20);this.life=o.life??rand(.25,.75);this.maxLife=this.life;this.size=o.size??rand(2,7);this.color=o.color??palette.ember;this.gravity=o.gravity??420;this.shape=o.shape??'square';this.front=o.front??true;}
  update(dt){this.life-=dt;this.vy+=this.gravity*dt;this.x+=this.vx*dt;this.y+=this.vy*dt;}
  draw(c,cameraX){if(this.life<=0)return;const a=clamp(this.life/this.maxLife,0,1),x=Math.round(this.x-cameraX),y=Math.round(this.y);c.globalAlpha=a;c.fillStyle=this.color;if(this.shape==='diamond'){c.save();c.translate(x,y);c.rotate(Math.PI/4);c.fillRect(-this.size/2,-this.size/2,this.size,this.size);c.restore();}else c.fillRect(x,y,this.size,this.size);c.globalAlpha=1;}
}
class FloatingText{
  constructor(x,y,text,color='#fff',size=18){this.x=x;this.y=y;this.text=text;this.color=color;this.size=size;this.life=.8;this.max=.8;}
  update(dt){this.life-=dt;this.y-=42*dt;}
  draw(c,cameraX){c.globalAlpha=clamp(this.life/this.max,0,1);c.fillStyle=this.color;c.font=`bold ${this.size}px monospace`;c.textAlign='center';c.fillText(this.text,Math.round(this.x-cameraX),Math.round(this.y));c.globalAlpha=1;}
}
class Projectile{
  constructor(x,y,vx,vy,owner,damage,kind='fire',life=2.4){Object.assign(this,{x,y,vx,vy,owner,damage,kind,life});this.w=kind==='wave'?70:18;this.h=kind==='wave'?28:18;this.dead=false;}
  update(dt,g){this.life-=dt;if(this.life<=0)this.dead=true;this.x+=this.vx*dt;this.y+=this.vy*dt;if(this.kind==='meteor')this.vy+=700*dt;if(chance(.35))g.particles.push(new Particle(this.x,this.y,{vx:rand(-20,20),vy:rand(-25,25),life:.25,size:rand(2,5),color:this.kind==='divine'?palette.gold:palette.ember,gravity:0}));if(this.owner==='enemy'&&!g.player.invulnerable&&rectsOverlap(this,g.player.bounds())){g.player.takeDamage(this.damage,Math.sign(this.vx)||1,g);this.dead=true;}if(this.owner==='player'){for(const e of g.enemies)if(!e.dead&&rectsOverlap(this,e.bounds())){e.takeDamage(this.damage,Math.sign(this.vx)||1,g);this.dead=true;break;}if(g.boss&&!g.boss.dead&&rectsOverlap(this,g.boss.bounds())){g.boss.takeDamage(this.damage,Math.sign(this.vx)||1,g);this.dead=true;}}if(this.y>FLOOR_Y+80)this.dead=true;}
  draw(c,cameraX){const x=Math.round(this.x-cameraX),y=Math.round(this.y);c.save();c.translate(x,y);if(this.kind==='wave'){c.fillStyle='#ffb25f';c.fillRect(-35,-8,70,16);c.fillStyle='#ff4c2d';c.fillRect(-28,-14,55,28);c.fillStyle='#fff0ad';c.fillRect(-15,-6,30,12);}else if(this.kind==='divine'){c.rotate(Math.atan2(this.vy,this.vx));c.fillStyle=palette.divine2;c.fillRect(-16,-4,32,8);c.fillStyle=palette.gold;c.fillRect(-9,-8,18,16);}else if(this.kind==='meteor'){c.fillStyle='#5a1723';c.fillRect(-12,-12,24,24);c.fillStyle='#ff6c37';c.fillRect(-8,-16,16,8);c.fillStyle='#ffd07c';c.fillRect(-4,-20,8,6);}else{c.fillStyle='#ffefad';c.fillRect(-4,-4,8,8);c.fillStyle='#ff5a2e';c.fillRect(-9,-9,18,18);}c.restore();}
}
class Pickup{
  constructor(x,y,type='heal'){Object.assign(this,{x,y,type});this.w=24;this.h=24;this.t=rand(0,6);this.dead=false;}
  update(dt,g){this.t+=dt;this.y+=Math.sin(this.t*3)*.15;if(rectsOverlap(this,g.player.bounds())){this.dead=true;audio.pickup();if(this.type==='heal'){g.player.hp=clamp(g.player.hp+28,0,g.player.maxHp);g.floaters.push(new FloatingText(this.x,this.y-12,'+28 HP','#7effa2'));g.toast('赤红药露：生命恢复');}else if(this.type==='mana'){g.player.mp=clamp(g.player.mp+38,0,g.player.maxMp);g.player.ult=clamp(g.player.ult+12,0,100);g.floaters.push(new FloatingText(this.x,this.y-12,'能量 +38','#7be7ff'));g.toast('火种碎片：能量与蓄能恢复');}else{g.player.buffTimer=10;g.floaters.push(new FloatingText(this.x,this.y-12,'攻击强化','#ffd77a'));g.toast('逐火圣徽：攻击提升 10 秒');}}}
  draw(c,cameraX){const x=Math.round(this.x-cameraX),y=Math.round(this.y);c.save();c.translate(x,y);c.rotate(this.t*.7);c.fillStyle=this.type==='heal'?'#ee4f64':this.type==='mana'?'#4ad1e1':'#f3c65a';c.fillRect(-9,-9,18,18);c.fillStyle='#fff0cd';c.fillRect(-3,-3,6,6);c.restore();}
}

class Player{
  constructor(){this.resetAll();}
  resetAll(){Object.assign(this,{x:120,y:FLOOR_Y-82,w:46,h:82,vx:0,vy:0,speed:300,jumpPower:690,maxHp:150,hp:150,maxMp:100,mp:100,ult:0,facing:1,onGround:true,coyote:0,jumpBuffer:0,attackTimer:0,combo:0,comboWindow:0,skillTimer:0,dodgeTimer:0,dodgeCooldown:0,invulnerable:false,hurtTimer:0,transformTimer:0,transformMax:16,buffTimer:0,state:'idle',animTime:0,kills:0,damageDone:0});}
  resetPosition(x=120){Object.assign(this,{x,y:FLOOR_Y-this.h,vx:0,vy:0,onGround:true,attackTimer:0,skillTimer:0,dodgeTimer:0,hurtTimer:0});}
  bounds(){return{x:this.x+8,y:this.y+5,w:this.w-16,h:this.h-6};}
  get transformed(){return this.transformTimer>0;} get attackMultiplier(){return(this.transformed?1.55:1)*(this.buffTimer>0?1.3:1);}
  update(dt,g){this.animTime+=dt;for(const k of['attackTimer','comboWindow','skillTimer','dodgeTimer','dodgeCooldown','hurtTimer','transformTimer','buffTimer','jumpBuffer','coyote'])this[k]=Math.max(0,this[k]-dt);this.invulnerable=this.dodgeTimer>0||this.hurtTimer>.45;this.mp=clamp(this.mp+(this.transformed?10:7)*dt,0,this.maxMp);if(this.hurtTimer>0){this.vy+=GRAVITY*dt;this.moveAndCollide(dt,g);return;}if(isPressed('jump'))this.jumpBuffer=.14;let input=(isDown('right')?1:0)-(isDown('left')?1:0);if(input)this.facing=input;if(isPressed('dodge')&&this.dodgeCooldown<=0){this.dodgeTimer=.28;this.dodgeCooldown=.85;this.vx=this.facing*720;this.vy=0;this.state='dodge';audio.dash();g.burst(this.x+this.w/2,this.y+this.h*.65,this.transformed?palette.gold:'#bd7e65',13);}if(this.dodgeTimer<=0){const target=input*this.speed*(this.transformed?1.12:1);this.vx=lerp(this.vx,target,clamp(dt*12*(this.onGround?1:.72),0,1));if(!input&&this.onGround)this.vx*=Math.pow(.0004,dt);if(this.jumpBuffer>0&&(this.onGround||this.coyote>0)){this.vy=-this.jumpPower;this.onGround=false;this.jumpBuffer=0;this.coyote=0;audio.jump();this.state='jump';}if(isPressed('attack'))this.attack(g);if(isPressed('skill'))this.skill(g);if(isPressed('ultimate'))this.ultimate(g);}this.vy+=GRAVITY*dt;this.moveAndCollide(dt,g);if(this.attackTimer<=0&&this.skillTimer<=0&&this.dodgeTimer<=0)this.state=!this.onGround?'jump':Math.abs(this.vx)>45?'run':'idle';}
  moveAndCollide(dt,g){const wasGround=this.onGround;this.x+=this.vx*dt;this.y+=this.vy*dt;this.onGround=false;const ground=g.getGroundY(this.x+this.w/2);if(this.y+this.h>=ground&&this.vy>=0){this.y=ground-this.h;this.vy=0;this.onGround=true;if(!wasGround)g.burst(this.x+this.w/2,ground-2,'#8d5e50',5);}if(wasGround&&!this.onGround)this.coyote=.12;this.x=clamp(this.x,0,g.levelWidth-this.w);for(const p of g.platforms){const b=this.bounds();if(this.vy>=0&&b.y+b.h<=p.y+18&&b.y+b.h+this.vy*dt>=p.y&&b.x+b.w>p.x&&b.x<p.x+p.w){this.y=p.y-this.h;this.vy=0;this.onGround=true;}}for(const h of g.hazards)if(rectsOverlap(this.bounds(),h)&&!this.invulnerable)this.takeDamage(h.damage||12,Math.sign(this.x-h.x)||1,g);}
  attack(g){if(this.attackTimer>.06)return;if(this.comboWindow<=0)this.combo=0;else this.combo=(this.combo+1)%3;this.attackTimer=(this.transformed?[.27,.3,.42]:[.23,.27,.38])[this.combo];this.comboWindow=.6;this.state='attack';const damage=Math.round([18,23,34][this.combo]*this.attackMultiplier),reach=this.transformed?105:76,h={x:this.facing>0?this.x+this.w-4:this.x-reach+4,y:this.y+12,w:reach,h:62};g.meleeHit(h,damage,this.facing,{knock:this.combo===2?390:180});if(this.transformed&&this.combo===2)g.projectiles.push(new Projectile(this.x+this.w/2,this.y+38,this.facing*680,0,'player',Math.round(28*this.attackMultiplier),'divine',1.6));audio.hit(this.combo===2);g.slash(h,this.facing,this.transformed,this.combo);}
  skill(g){if(this.skillTimer>0||this.attackTimer>.08)return;const cost=this.transformed?20:28;if(this.mp<cost){g.toast('能量不足');return;}this.mp-=cost;this.skillTimer=this.transformed?.85:.72;this.state='skill';audio.skill();if(this.transformed){g.screenShake=.28;g.flash='#fff0a6';g.flashAlpha=.5;for(let i=-2;i<=2;i++)setTimeout(()=>{if(g.state==='playing')g.projectiles.push(new Projectile(this.x+this.w/2+i*24,this.y+18-Math.abs(i)*10,this.facing*(520+Math.abs(i)*45),i*35,'player',Math.round(34*this.attackMultiplier),'divine',1.8));},Math.abs(i)*50);g.areaHit({x:this.x-125,y:this.y-80,w:250,h:200},Math.round(42*this.attackMultiplier),this.facing,450);g.burst(this.x+this.w/2,this.y+30,palette.gold,34);}else{const box={x:this.facing>0?this.x+8:this.x-145,y:this.y-10,w:180,h:105};g.areaHit(box,Math.round(46*this.attackMultiplier),this.facing,480);g.waveArc(this.x+this.w/2,this.y+42,this.facing,palette.ember);g.screenShake=.16;}}
  ultimate(g){if(this.transformed){g.toast(`神厄形态剩余 ${this.transformTimer.toFixed(1)} 秒`);return;}if(this.ult<100){g.toast(`终结技蓄能 ${Math.floor(this.ult)}%`);return;}this.ult=0;this.transformTimer=this.transformMax;this.hp=clamp(this.hp+42,0,this.maxHp);this.mp=this.maxMp;this.state='transform';this.invulnerable=true;audio.ult();g.startTransformation();}
  takeDamage(amount,dir,g){if(this.invulnerable)return;this.hp-=amount;this.hurtTimer=.62;this.vx=dir*260;this.vy=-280;this.state='hurt';audio.hurt();g.screenShake=.25;g.flash='#7a1323';g.flashAlpha=.5;g.burst(this.x+this.w/2,this.y+30,'#ff3e4b',12);g.floaters.push(new FloatingText(this.x+this.w/2,this.y-10,`-${amount}`,'#ff7b82',22));if(this.hp<=0){this.hp=0;g.playerDied();}}
  draw(c,cameraX){drawPlayer(c,Math.round(this.x-cameraX),Math.round(this.y),this);}
}

class Enemy{
  constructor(x,y,type='emberling'){Object.assign(this,{x,y,type,dead:false,anim:rand(0,3),attackCd:rand(.3,1),hurt:0,vx:0,vy:0,facing:-1,state:'idle',shield:0});this.setup();}
  setup(){Object.assign(this,{emberling:{w:42,h:54,hp:68,speed:105,damage:12,color:'#d44c35'},archer:{w:42,h:64,hp:62,speed:70,damage:10,color:'#845174'},hound:{w:64,h:44,hp:88,speed:155,damage:15,color:'#8c342e'},elite:{w:72,h:94,hp:310,speed:80,damage:22,color:'#b35334'}}[this.type]);this.maxHp=this.hp;if(this.type==='elite')this.shield=90;}
  bounds(){return{x:this.x+4,y:this.y+4,w:this.w-8,h:this.h-4};}
  update(dt,g){if(this.dead)return;this.anim+=dt;this.attackCd-=dt;this.hurt=Math.max(0,this.hurt-dt);this.vy+=GRAVITY*dt;const p=g.player,dx=(p.x+p.w/2)-(this.x+this.w/2);this.facing=Math.sign(dx)||this.facing;if(this.hurt<=0){if(this.type==='archer'){if(Math.abs(dx)<430&&this.attackCd<=0){this.attackCd=1.8;this.state='attack';g.projectiles.push(new Projectile(this.x+this.w/2,this.y+20,this.facing*280,-30,'enemy',this.damage,'fire',2.3));audio.tone(140,.08,'square',.018,80);}else this.vx=Math.abs(dx)<210?-this.facing*this.speed:Math.abs(dx)>360?this.facing*this.speed:0;}else if(this.type==='hound'){if(Math.abs(dx)<260&&this.attackCd<=0){this.attackCd=2;this.state='charge';this.vx=this.facing*460;}else if(this.state!=='charge')this.vx=this.facing*this.speed;if(this.state==='charge'&&this.attackCd<1.55)this.state='walk';}else if(this.type==='elite'){if(Math.abs(dx)<125&&this.attackCd<=0){this.attackCd=2.2;this.state='slam';setTimeout(()=>{if(!this.dead&&g.state==='playing'){g.areaEnemyHit({x:this.x-55,y:FLOOR_Y-50,w:this.w+110,h:50},this.damage,this.facing);g.screenShake=.22;g.waveArc(this.x+this.w/2,FLOOR_Y-25,this.facing,'#ff763f');}},420);this.vx=0;}else this.vx=Math.abs(dx)>90?this.facing*this.speed:0;}else{if(Math.abs(dx)<70&&this.attackCd<=0){this.attackCd=1.25;this.state='attack';setTimeout(()=>{if(!this.dead&&g.state==='playing')g.areaEnemyHit({x:this.facing>0?this.x+20:this.x-38,y:this.y+12,w:60,h:this.h-12},this.damage,this.facing);},220);this.vx=0;}else this.vx=Math.abs(dx)>48?this.facing*this.speed:0;}}this.x+=this.vx*dt;this.y+=this.vy*dt;const gy=g.getGroundY(this.x+this.w/2);if(this.y+this.h>=gy){this.y=gy-this.h;this.vy=0;}if(rectsOverlap(this.bounds(),p.bounds())&&!p.invulnerable&&Math.abs(this.vx)>280)p.takeDamage(this.damage,this.facing,g);}
  takeDamage(amount,dir,g){if(this.dead)return;if(this.shield>0){const block=Math.min(this.shield,amount*.7);this.shield-=block;amount-=block;g.floaters.push(new FloatingText(this.x+this.w/2,this.y-12,`盾 -${Math.round(block)}`,'#ffd27c',15));}amount=Math.max(1,Math.round(amount));this.hp-=amount;this.hurt=.18;this.vx=dir*170;g.player.ult=clamp(g.player.ult+amount*.23,0,100);g.player.damageDone+=amount;g.floaters.push(new FloatingText(this.x+this.w/2,this.y,`${amount}`,g.player.transformed?'#ffe986':'#fff0e0',20));g.burst(this.x+this.w/2,this.y+this.h/2,this.color,7);if(this.hp<=0){this.dead=true;g.player.kills++;g.burst(this.x+this.w/2,this.y+this.h/2,this.color,25);audio.hit(true);if(chance(this.type==='elite'?.95:.28))g.pickups.push(new Pickup(this.x+this.w/2,this.y+10,chance(.5)?'heal':chance(.65)?'mana':'buff'));}}
  draw(c,cameraX){drawEnemy(c,Math.round(this.x-cameraX),Math.round(this.y),this);if(this.type==='elite'&&!this.dead)drawMiniBar(c,this.x-cameraX,this.y-17,this.w,this.hp/this.maxHp,this.shield>0?this.shield/90:0);}
}

class Boss{
  constructor(x){Object.assign(this,{x,y:FLOOR_Y-170,w:116,h:170,maxHp:1800,hp:1800,dead:false,phase:1,anim:0,attackCd:1.5,pattern:0,vx:0,facing:-1,hurt:0,name:'绝灭大君·焚风'});}
  bounds(){return{x:this.x+12,y:this.y+8,w:this.w-24,h:this.h-8};}
  update(dt,g){if(this.dead)return;this.anim+=dt;this.attackCd-=dt;this.hurt=Math.max(0,this.hurt-dt);const p=g.player,dx=(p.x+p.w/2)-(this.x+this.w/2);this.facing=Math.sign(dx)||this.facing;const ratio=this.hp/this.maxHp,newPhase=ratio>.66?1:ratio>.33?2:3;if(newPhase!==this.phase){this.phase=newPhase;g.toast(`焚风进入第 ${this.phase} 阶段`);g.screenShake=.5;g.flash='#ff3d25';g.flashAlpha=.7;g.burst(this.x+this.w/2,this.y+70,palette.ember,60);}if(this.attackCd<=0&&this.hurt<=0){this.pattern=(this.pattern+1)%(this.phase+2);this.attackCd=Math.max(.7,2.15-this.phase*.28);this.performPattern(g);}if(this.hurt<=0&&this.pattern===0&&Math.abs(dx)>160)this.vx=lerp(this.vx,this.facing*(70+this.phase*20),dt*3);else this.vx*=Math.pow(.05,dt);this.x+=this.vx*dt;this.x=clamp(this.x,g.levelStart+500,g.levelWidth-this.w-60);}
  performPattern(g){if(this.pattern===0){this.vx=this.facing*(this.phase===3?640:500);setTimeout(()=>{if(!this.dead){g.areaEnemyHit({x:this.facing>0?this.x+40:this.x-100,y:this.y+35,w:160,h:120},24+this.phase*5,this.facing);g.screenShake=.3;}},250);}else if(this.pattern===1){for(let i=0;i<3+this.phase;i++)setTimeout(()=>{if(!this.dead)g.projectiles.push(new Projectile(this.x+this.w/2,this.y+65,this.facing*(280+i*35),-220+i*75,'enemy',12+this.phase*3,'fire',2.8));},i*90);}else if(this.pattern===2){for(let i=0;i<4+this.phase*2;i++){const tx=clamp(g.player.x+rand(-260,260),g.levelStart+80,g.levelWidth-80);g.telegraphs.push({x:tx,y:FLOOR_Y-12,w:46,h:18,life:.75,max:.75});setTimeout(()=>{if(!this.dead)g.projectiles.push(new Projectile(tx,FLOOR_Y-560,rand(-30,30),300,'enemy',16+this.phase*3,'meteor',2.5));},700+i*90);}}else{g.screenShake=.5;g.flash='#ff6b32';g.flashAlpha=.55;for(let d=-1;d<=1;d+=2)for(let i=0;i<3;i++)setTimeout(()=>g.projectiles.push(new Projectile(this.x+this.w/2,FLOOR_Y-28,d*(300+i*55),0,'enemy',20,'wave',2.6)),i*120);}audio.tone(72,.34,'sawtooth',.055,120);}
  takeDamage(amount,dir,g){if(this.dead)return;amount=Math.max(1,Math.round(amount*(this.phase===3?.9:1)));this.hp-=amount;this.hurt=.06;g.player.ult=clamp(g.player.ult+amount*.11,0,100);g.player.damageDone+=amount;g.floaters.push(new FloatingText(this.x+this.w/2,this.y+15,`${amount}`,g.player.transformed?'#fff49c':'#ffe1c7',22));g.burst(this.x+this.w/2,this.y+70,this.phase===3?'#ff243b':'#ff6c37',9);if(this.hp<=0){this.hp=0;this.dead=true;g.bossDefeated();}}
  draw(c,cameraX){drawBoss(c,Math.round(this.x-cameraX),Math.round(this.y),this);}
}

const LEVELS=[
{name:'第一幕 · 焦土行军',width:3600,tint:'#471623',sky:'#140712',ground:'#311018',accent:'#ff6c38',story:[['白厄','又一次，太阳从灰烬里升起。但这次……我会让它照见终点。'],['？？？','前方的火种已经异变。那些倒下的士兵，正被毁灭的余烬重新驱使。'],['白厄','那就让剑刃替他们熄灭痛苦。']],spawns:[[620,'emberling'],[900,'emberling'],[1250,'archer'],[1530,'hound'],[1880,'emberling'],[2080,'archer'],[2460,'hound'],[2730,'emberling'],[2900,'emberling'],[3160,'elite']],platforms:[{x:780,y:500,w:240},{x:1460,y:455,w:220},{x:2240,y:510,w:260},{x:2820,y:445,w:210}],hazards:[{x:1100,y:606,w:110,h:16,damage:10},{x:1980,y:606,w:120,h:16,damage:12},{x:2650,y:606,w:100,h:16,damage:12}]},
{name:'第二幕 · 灰烬城垒',width:4200,tint:'#35203d',sky:'#0d0815',ground:'#241323',accent:'#a8515a',story:[['神秘残响','城垒深处保存着一枚未熄的核心火种。得到它，神厄之力将回应你。'],['白厄','力量从来不是答案。可在答案到来前，我必须握住它。']],spawns:[[560,'archer'],[900,'hound'],[1200,'emberling'],[1420,'emberling'],[1700,'elite'],[2170,'archer'],[2400,'archer'],[2730,'hound'],[3100,'elite'],[3450,'emberling'],[3650,'hound'],[3890,'elite']],platforms:[{x:520,y:480,w:260},{x:1040,y:410,w:230},{x:1510,y:505,w:280},{x:2180,y:450,w:220},{x:2700,y:390,w:270},{x:3330,y:475,w:300}],hazards:[{x:800,y:603,w:130,h:20,damage:14},{x:1840,y:603,w:180,h:20,damage:15},{x:3000,y:603,w:160,h:20,damage:16}]},
{name:'终幕 · 炉心王座',width:3400,tint:'#60151c',sky:'#110305',ground:'#380d12',accent:'#ff3b26',story:[['绝灭大君·焚风','背负三千万次轮回的残骸，你仍妄想守护一个注定焚毁的世界？'],['白厄','正因为见过它毁灭无数次，我才知道——每一次重来，都不是毫无意义。'],['绝灭大君·焚风','那么，就让你的希望成为最后一把薪柴。']],spawns:[[550,'hound'],[820,'archer'],[1080,'elite'],[1420,'emberling'],[1620,'emberling'],[1900,'elite']],platforms:[{x:650,y:480,w:250},{x:1280,y:430,w:230},{x:1840,y:500,w:210}],hazards:[{x:950,y:604,w:160,h:18,damage:18},{x:1550,y:604,w:150,h:18,damage:18}]}
];
const STORY_END=[['绝灭大君·焚风','不可能……毁灭的火，竟会被凡人的意志压过……'],['白厄','不是我一个人的意志。每一个不肯放弃的人，都在这里。'],['神秘残响','炉心正在坍缩。逐火者，新的道路已经开启。'],['白厄','那就走吧。太阳尚未升起之前，总要有人先成为光。']];

class Game{
  constructor(){Object.assign(this,{state:'boot',player:new Player(),levelIndex:0,levelWidth:3600,levelStart:0,cameraX:0,enemies:[],projectiles:[],pickups:[],particles:[],floaters:[],slashes:[],telegraphs:[],platforms:[],hazards:[],boss:null,time:0,levelTime:0,screenShake:0,flash:null,flashAlpha:0,dialogueQueue:[],dialogueCallback:null,currentDialogue:0,lastTime:performance.now(),toastTimer:0,waveBanner:0,transformationCinematic:0,stats:{deaths:0,totalTime:0}});this.bindUI();this.boot();}
  bindUI(){document.getElementById('start-btn').onclick=()=>this.newGame();document.getElementById('how-btn').onclick=()=>{UI.title.classList.add('hidden');UI.how.classList.remove('hidden');UI.how.classList.add('visible');};document.getElementById('how-back').onclick=()=>{UI.how.classList.add('hidden');UI.how.classList.remove('visible');UI.title.classList.remove('hidden');UI.title.classList.add('visible');};UI.continueBtn.onclick=()=>this.continueGame();document.getElementById('resume-btn').onclick=()=>this.resume();document.getElementById('restart-btn').onclick=()=>{this.hidePause();this.startLevel(this.levelIndex,true);};document.getElementById('quit-btn').onclick=()=>{this.hidePause();this.showTitle();};UI.resultBtn.onclick=()=>this.handleResult();window.addEventListener('keydown',e=>{const a=keyAction(e.code);if(a){if(!keys.has(a))pressed.add(a);keys.add(a);if(['jump','left','right'].includes(a))e.preventDefault();}if((e.code==='Escape'||e.code==='KeyP')&&this.state==='playing')this.pause();else if((e.code==='Escape'||e.code==='KeyP')&&this.state==='paused')this.resume();if(this.state==='dialogue'&&(e.code==='Enter'||e.code==='Space')){e.preventDefault();this.nextDialogue();}});window.addEventListener('keyup',e=>{const a=keyAction(e.code);if(a)keys.delete(a);});window.addEventListener('blur',()=>{if(this.state==='playing')this.pause();});UI.dialogue.addEventListener('pointerdown',()=>{if(this.state==='dialogue')this.nextDialogue();});document.querySelectorAll('#mobile-controls button').forEach(btn=>{const a=btn.dataset.action,down=e=>{e.preventDefault();audio.ensure();if(!touchState.has(a))pressed.add(a);touchState.add(a);btn.classList.add('pressed');},up=e=>{e.preventDefault();touchState.delete(a);btn.classList.remove('pressed');};btn.addEventListener('pointerdown',down);btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up);btn.addEventListener('pointerleave',up);});}
  boot(){let p=0;const timer=setInterval(()=>{p+=rand(8,17);UI.loadingBar.style.width=`${Math.min(100,p)}%`;if(p>=100){clearInterval(timer);setTimeout(()=>{UI.loading.classList.add('hidden');this.showTitle();},280);}},90);requestAnimationFrame(t=>this.loop(t));}
  showTitle(){this.state='title';UI.title.classList.remove('hidden');UI.title.classList.add('visible');UI.result.classList.add('hidden');UI.dialogue.classList.add('hidden');const save=this.loadSave();if(save){UI.continueBtn.classList.remove('hidden');UI.continueBtn.textContent=`继续：${LEVELS[save.levelIndex]?.name||'远征'}`;}else UI.continueBtn.classList.add('hidden');}
  newGame(){audio.ensure();localStorage.removeItem('phainon-emberfall-save');UI.title.classList.add('hidden');this.levelIndex=0;this.player.resetAll();this.stats={deaths:0,totalTime:0};this.startLevel(0,false);}
  continueGame(){const s=this.loadSave();if(!s)return this.newGame();audio.ensure();UI.title.classList.add('hidden');this.levelIndex=clamp(s.levelIndex||0,0,LEVELS.length-1);this.player.resetAll();this.player.hp=clamp(s.hp||this.player.maxHp,1,this.player.maxHp);this.player.ult=clamp(s.ult||0,0,100);this.stats=s.stats||{deaths:0,totalTime:0};this.startLevel(this.levelIndex,false);}
  save(){localStorage.setItem('phainon-emberfall-save',JSON.stringify({levelIndex:this.levelIndex,hp:this.player.hp,ult:this.player.ult,stats:this.stats}));}
  loadSave(){try{return JSON.parse(localStorage.getItem('phainon-emberfall-save'));}catch{return null;}}
  startLevel(index,retry=false){this.levelIndex=index;const l=LEVELS[index];this.levelWidth=l.width;this.levelStart=0;this.cameraX=0;this.enemies=l.spawns.map(([x,t])=>new Enemy(x,FLOOR_Y-80,t));this.platforms=l.platforms.map(x=>({...x}));this.hazards=l.hazards.map(x=>({...x}));this.projectiles=[];this.pickups=[];this.particles=[];this.floaters=[];this.slashes=[];this.telegraphs=[];this.boss=null;this.levelTime=0;this.waveBanner=2.5;this.player.resetPosition(120);if(!retry){this.player.hp=clamp(this.player.hp+22,0,this.player.maxHp);this.player.mp=this.player.maxMp;}if(index===2)this.bossSpawned=false;const begin=()=>{this.state='playing';this.toast(l.name);};if(!retry)this.showDialogue(l.story,begin);else begin();}
  getGroundY(x){let y=FLOOR_Y;if(this.levelIndex===0&&x>1650&&x<1760)y=FLOOR_Y+12;if(this.levelIndex===1&&x>2450&&x<2580)y=FLOOR_Y-20;return y;}
  update(dt){this.time+=dt;if(this.state!=='playing'){pressed.clear();return;}this.levelTime+=dt;this.stats.totalTime+=dt;this.screenShake=Math.max(0,this.screenShake-dt);this.flashAlpha=Math.max(0,this.flashAlpha-dt*2.8);this.waveBanner=Math.max(0,this.waveBanner-dt);this.transformationCinematic=Math.max(0,this.transformationCinematic-dt);this.toastTimer=Math.max(0,this.toastTimer-dt);if(this.toastTimer<=0)UI.toast.classList.add('hidden');this.player.update(dt,this);for(const e of this.enemies)e.update(dt,this);for(const p of this.projectiles)p.update(dt,this);for(const p of this.pickups)p.update(dt,this);for(const p of this.particles)p.update(dt);for(const f of this.floaters)f.update(dt);if(this.boss)this.boss.update(dt,this);this.enemies=this.enemies.filter(e=>!e.dead||e.anim%1<.22);this.projectiles=this.projectiles.filter(p=>!p.dead);this.pickups=this.pickups.filter(p=>!p.dead);this.particles=this.particles.filter(p=>p.life>0);this.floaters=this.floaters.filter(f=>f.life>0);this.slashes=this.slashes.filter(s=>(s.life-=dt)>0);this.telegraphs=this.telegraphs.filter(t=>(t.life-=dt)>0);const target=clamp(this.player.x-W*.38,0,this.levelWidth-W);this.cameraX=lerp(this.cameraX,target,clamp(dt*5.5,0,1));if(this.levelIndex===2&&!this.bossSpawned&&this.player.x>2200){this.bossSpawned=true;this.boss=new Boss(3000);this.toast('最终目标：击败绝灭大君·焚风');this.waveBanner=2.8;}const alive=this.enemies.some(e=>!e.dead);if(!alive&&this.levelIndex<2&&this.player.x>this.levelWidth-520)this.levelComplete();pressed.clear();}
  draw(){const shake=this.screenShake>0?rand(-9,9)*this.screenShake/.3:0;ctx.save();ctx.translate(shake,shake*.35);this.drawBackground(ctx);this.drawWorld(ctx);ctx.restore();this.drawHUD(ctx);if(this.waveBanner>0)this.drawBanner(ctx);if(this.transformationCinematic>0)this.drawTransformationOverlay(ctx);if(this.flashAlpha>0&&this.flash){ctx.globalAlpha=this.flashAlpha;ctx.fillStyle=this.flash;ctx.fillRect(0,0,W,H);ctx.globalAlpha=1;}}
  drawBackground(c){const l=LEVELS[this.levelIndex]||LEVELS[0],grad=c.createLinearGradient(0,0,0,H);grad.addColorStop(0,l.sky);grad.addColorStop(.65,l.tint);grad.addColorStop(1,l.ground);c.fillStyle=grad;c.fillRect(0,0,W,H);c.fillStyle='rgba(255,110,55,.16)';for(let i=0;i<7;i++){const x=((i*260-this.cameraX*.08)%1600+1600)%1600-100,y=90+(i%3)*62;c.fillRect(x,y,170,5);c.fillRect(x+30,y-12,100,4);}c.fillStyle='#130713';for(let i=0;i<10;i++){const x=((i*210-this.cameraX*.18)%2200+2200)%2200-130,h=90+(i%4)*45;c.fillRect(x,FLOOR_Y-h-70,78,h);c.fillRect(x+16,FLOOR_Y-h-104,12,34);c.fillRect(x+48,FLOOR_Y-h-125,10,55);}c.fillStyle='rgba(255,65,30,.18)';for(let i=0;i<22;i++){const x=((i*117-this.cameraX*.35)%2600+2600)%2600,h=20+(i*37)%90;c.fillRect(x,FLOOR_Y-60-h,7,h);}for(let i=0;i<14;i++){const x=((i*173+this.time*18-this.cameraX*.11)%1500+1500)%1500,y=80+(i*71)%420;c.fillStyle=i%3===0?'#ff7440':'#a73532';c.fillRect(x,y,2+(i%2),2+(i%3));}}
  drawWorld(c){const l=LEVELS[this.levelIndex];c.fillStyle=l.ground;c.fillRect(0,FLOOR_Y,W,H-FLOOR_Y);c.fillStyle=l.accent;c.fillRect(0,FLOOR_Y,W,4);c.fillStyle='#16080d';for(let x=-((this.cameraX*.8)%64);x<W;x+=64){c.fillRect(x,FLOOR_Y+14,42,8);c.fillRect(x+24,FLOOR_Y+36,54,7);}for(const h of this.hazards){const x=h.x-this.cameraX;c.fillStyle='#671727';c.fillRect(x,h.y,h.w,h.h);c.fillStyle='#ff6536';for(let i=0;i<h.w;i+=18){const flame=8+Math.sin(this.time*8+i)*5;c.fillRect(x+i,h.y-flame,10,flame);c.fillStyle='#ffd072';c.fillRect(x+i+3,h.y-flame,4,Math.max(3,flame*.45));c.fillStyle='#ff6536';}}for(const p of this.platforms){const x=p.x-this.cameraX;c.fillStyle='#5b2830';c.fillRect(x,p.y,p.w,18);c.fillStyle='#bf5a43';c.fillRect(x,p.y,p.w,4);c.fillStyle='#24101b';for(let i=10;i<p.w;i+=34)c.fillRect(x+i,p.y+18,18,12);}for(const t of this.telegraphs){const a=.3+.5*Math.sin((t.max-t.life)*20);c.globalAlpha=a;c.fillStyle='#ff2f25';c.fillRect(t.x-this.cameraX-t.w/2,FLOOR_Y-8,t.w,8);c.globalAlpha=1;}for(const p of this.pickups)p.draw(c,this.cameraX);for(const e of this.enemies)e.draw(c,this.cameraX);if(this.boss)this.boss.draw(c,this.cameraX);this.player.draw(c,this.cameraX);for(const p of this.projectiles)p.draw(c,this.cameraX);for(const s of this.slashes)this.drawSlash(c,s);for(const p of this.particles)p.draw(c,this.cameraX);for(const f of this.floaters)f.draw(c,this.cameraX);}
  drawSlash(c,s){const x=s.x-this.cameraX;c.save();c.globalAlpha=s.life/s.max;c.strokeStyle=s.color;c.lineWidth=s.transformed?13:8;c.beginPath();c.arc(x,s.y,s.r,s.facing>0?-.8*Math.PI:.2*Math.PI,s.facing>0?.65*Math.PI:1.65*Math.PI);c.stroke();c.restore();}
  drawHUD(c){if(!['playing','paused'].includes(this.state))return;c.save();c.fillStyle='rgba(10,4,10,.8)';c.fillRect(28,24,430,100);c.strokeStyle='rgba(255,210,150,.32)';c.strokeRect(28,24,430,100);c.fillStyle='#f5dfc6';c.font='bold 18px monospace';c.textAlign='left';c.fillText(this.player.transformed?'神厄 · 白厄':'白厄',48,49);drawBar(c,48,59,365,16,this.player.hp/this.player.maxHp,palette.hp,'生命');drawBar(c,48,82,365,12,this.player.mp/this.player.maxMp,palette.mp,'能量');drawBar(c,48,101,365,10,this.player.ult/100,palette.ult,'终结');c.fillStyle='rgba(10,4,10,.78)';c.fillRect(W-340,24,312,68);c.strokeStyle='rgba(255,210,150,.3)';c.strokeRect(W-340,24,312,68);c.fillStyle='#f5dfc6';c.font='bold 17px monospace';c.fillText(LEVELS[this.levelIndex].name,W-320,50);c.fillStyle='#b89d99';c.font='14px monospace';c.fillText(`击破 ${this.player.kills}  ·  ${formatTime(this.levelTime)}`,W-320,74);if(this.player.transformed){c.fillStyle='rgba(70,48,9,.75)';c.fillRect(W/2-170,24,340,42);c.strokeStyle='#ffe88a';c.strokeRect(W/2-170,24,340,42);c.fillStyle='#fff2a7';c.font='bold 17px monospace';c.textAlign='center';c.fillText(`神厄形态  ${this.player.transformTimer.toFixed(1)}s`,W/2,51);}if(this.boss&&!this.boss.dead){const bw=650,bx=(W-bw)/2,by=H-52;c.fillStyle='rgba(10,2,5,.88)';c.fillRect(bx-18,by-28,bw+36,56);c.fillStyle='#ffcfaa';c.font='bold 18px monospace';c.textAlign='center';c.fillText(this.boss.name,W/2,by-7);drawBar(c,bx,by,bw,15,this.boss.hp/this.boss.maxHp,'#d52a35','');}c.restore();}
  drawBanner(c){const a=clamp(this.waveBanner/.6,0,1)*clamp((2.5-this.waveBanner)/.35,0,1);c.globalAlpha=a;c.fillStyle='rgba(9,3,8,.78)';c.fillRect(0,H/2-58,W,116);c.fillStyle='#ffe2a7';c.textAlign='center';c.font='bold 38px serif';c.fillText(this.boss&&this.bossSpawned?'最终战 · 炉心焚灭':LEVELS[this.levelIndex].name,W/2,H/2-2);c.fillStyle='#c57b58';c.font='15px monospace';c.fillText('逐火之路不会因灰烬而终止',W/2,H/2+29);c.globalAlpha=1;}
  drawTransformationOverlay(c){const a=clamp(this.transformationCinematic/.25,0,1);c.globalAlpha=a*.38;c.fillStyle='#fff0a5';c.fillRect(0,0,W,H);c.globalAlpha=a;c.fillStyle='rgba(16,8,10,.88)';c.fillRect(0,H/2-90,W,180);c.fillStyle='#fff4bd';c.textAlign='center';c.font='bold 52px serif';c.fillText('终结技 · 神厄降临',W/2,H/2+5);c.font='18px monospace';c.fillStyle='#e7b85d';c.fillText('以千万次轮回为刃，斩开毁灭的长夜',W/2,H/2+44);c.globalAlpha=1;}
  showDialogue(lines,callback){this.state='dialogue';this.dialogueQueue=lines;this.currentDialogue=0;this.dialogueCallback=callback;UI.dialogue.classList.remove('hidden');this.renderDialogue();}
  renderDialogue(){const[speaker,text]=this.dialogueQueue[this.currentDialogue];UI.speaker.textContent=speaker;UI.dialogueText.textContent=text;UI.portrait.innerHTML='';const pc=document.createElement('canvas');pc.width=180;pc.height=170;const pctx=pc.getContext('2d');pctx.imageSmoothingEnabled=false;if(speaker==='白厄')drawPortraitPhainon(pctx);else if(speaker.includes('焚风'))drawPortraitBoss(pctx);else drawPortraitEcho(pctx);UI.portrait.appendChild(pc);}
  nextDialogue(){this.currentDialogue++;if(this.currentDialogue>=this.dialogueQueue.length){UI.dialogue.classList.add('hidden');const cb=this.dialogueCallback;this.dialogueCallback=null;if(cb)cb();}else this.renderDialogue();}
  pause(){if(this.state!=='playing')return;this.state='paused';UI.pause.classList.remove('hidden');UI.pause.classList.add('visible');}
  resume(){if(this.state!=='paused')return;this.state='playing';this.hidePause();this.lastTime=performance.now();}
  hidePause(){UI.pause.classList.add('hidden');UI.pause.classList.remove('visible');}
  playerDied(){this.state='result';this.stats.deaths++;UI.resultKicker.textContent='远征中断';UI.resultTitle.textContent='火种暂时熄灭';UI.resultText.textContent='轮回并非失败。记住敌人的节奏，再一次踏入焦土。';UI.resultStats.textContent=`本关时间 ${formatTime(this.levelTime)} · 击破 ${this.player.kills} · 造成伤害 ${Math.round(this.player.damageDone)}`;UI.resultBtn.textContent='重新挑战';UI.result.classList.remove('hidden');UI.result.classList.add('visible');this.resultAction='retry';}
  levelComplete(){if(this.state!=='playing')return;this.state='result';this.save();UI.resultKicker.textContent='关卡完成';UI.resultTitle.textContent=LEVELS[this.levelIndex].name;UI.resultText.textContent='核心火种已经回响。前方的战场正在开启。';UI.resultStats.textContent=`用时 ${formatTime(this.levelTime)} · 击破 ${this.player.kills} · 生命 ${Math.ceil(this.player.hp)}/${this.player.maxHp}`;UI.resultBtn.textContent='进入下一幕';UI.result.classList.remove('hidden');UI.result.classList.add('visible');this.resultAction='next';}
  bossDefeated(){this.state='dialogue';this.screenShake=.8;this.flash='#fff0b0';this.flashAlpha=1;this.burst(this.boss.x+this.boss.w/2,this.boss.y+80,'#ffd869',120);setTimeout(()=>this.showDialogue(STORY_END,()=>this.showVictory()),900);}
  showVictory(){this.state='result';localStorage.removeItem('phainon-emberfall-save');UI.resultKicker.textContent='远征完成';UI.resultTitle.textContent='逐火残响';UI.resultText.textContent='焚烧地狱的长夜被剑光切开。新的轮回不再沿着旧日轨迹运行。';UI.resultStats.textContent=`总用时 ${formatTime(this.stats.totalTime)} · 阵亡 ${this.stats.deaths} · 击破 ${this.player.kills}`;UI.resultBtn.textContent='返回标题';UI.result.classList.remove('hidden');UI.result.classList.add('visible');this.resultAction='title';}
  handleResult(){UI.result.classList.add('hidden');UI.result.classList.remove('visible');if(this.resultAction==='retry'){this.player.hp=this.player.maxHp;this.player.mp=this.player.maxMp;this.startLevel(this.levelIndex,true);}else if(this.resultAction==='next'){this.levelIndex++;this.player.kills=0;this.player.damageDone=0;this.startLevel(this.levelIndex,false);}else this.showTitle();}
  startTransformation(){this.transformationCinematic=1.45;this.screenShake=.75;this.flash='#fff3ad';this.flashAlpha=.85;this.burst(this.player.x+this.player.w/2,this.player.y+35,palette.gold,70);this.areaHit({x:this.player.x-220,y:this.player.y-170,w:480,h:300},85,1,600);this.toast('神厄形态：普攻与战技已强化');}
  meleeHit(box,damage,dir,o={}){let hit=false;for(const e of this.enemies)if(!e.dead&&rectsOverlap(box,e.bounds())){e.takeDamage(damage,dir,this);e.vx+=dir*(o.knock||180);hit=true;}if(this.boss&&!this.boss.dead&&rectsOverlap(box,this.boss.bounds())){this.boss.takeDamage(damage,dir,this);hit=true;}if(hit)this.screenShake=Math.max(this.screenShake,.08);}
  areaHit(box,damage,dir,knock=250){this.meleeHit(box,damage,dir,{knock});}
  areaEnemyHit(box,damage,dir){if(!this.player.invulnerable&&rectsOverlap(box,this.player.bounds()))this.player.takeDamage(damage,dir,this);}
  slash(box,facing,transformed,combo){this.slashes.push({x:facing>0?box.x+8:box.x+box.w-8,y:box.y+box.h*.52,r:45+combo*10,life:.18,max:.18,facing,transformed,color:transformed?palette.divine2:combo===2?'#ffd38a':'#ff7b46'});}
  waveArc(x,y,facing,color){this.slashes.push({x,y,r:105,life:.3,max:.3,facing,transformed:true,color});}
  burst(x,y,color,count=10){for(let i=0;i<count;i++)this.particles.push(new Particle(x,y,{vx:rand(-260,260),vy:rand(-300,100),life:rand(.22,.8),size:rand(2,8),color,gravity:rand(100,700),shape:chance(.35)?'diamond':'square'}));}
  toast(text,duration=2.2){UI.toast.textContent=text;UI.toast.classList.remove('hidden');this.toastTimer=duration;}
  loop(t){const dt=Math.min(.033,(t-this.lastTime)/1000||0);this.lastTime=t;this.update(dt);this.draw();requestAnimationFrame(x=>this.loop(x));}
}

function isDown(a){return keys.has(a)||touchState.has(a);}function isPressed(a){return pressed.has(a);}function keyAction(code){return({KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',KeyW:'jump',ArrowUp:'jump',Space:'jump',ShiftLeft:'dodge',ShiftRight:'dodge',KeyJ:'attack',KeyK:'skill',KeyL:'ultimate'}[code]);}function formatTime(s){return`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;}
function drawBar(c,x,y,w,h,p,color,label){p=clamp(p,0,1);c.fillStyle='rgba(255,255,255,.08)';c.fillRect(x,y,w,h);c.fillStyle=color;c.fillRect(x,y,Math.round(w*p),h);c.fillStyle='rgba(255,255,255,.34)';c.fillRect(x,y,Math.round(w*p),2);if(label){c.font='bold 10px monospace';c.fillStyle='#fff1df';c.textAlign='left';c.fillText(label,x+5,y+h-3);}}
function drawMiniBar(c,x,y,w,p,shield=0){c.fillStyle='#16070d';c.fillRect(x,y,w,7);c.fillStyle='#c93d42';c.fillRect(x,y,w*clamp(p,0,1),7);if(shield>0){c.fillStyle='#e3b65d';c.fillRect(x,y-5,w*clamp(shield,0,1),3);}}
function px(c,x,y,w,h,color){c.fillStyle=color;c.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
function drawPlayer(c,x,y,p){const t=p.animTime,frame=Math.floor(t*(p.state==='run'?12:7))%4,bob=p.state==='idle'?[0,-1,0,1][frame]:p.state==='run'?[0,2,0,-2][frame]:0,flip=p.facing<0;c.save();c.translate(x+(flip?p.w:0),y+bob);c.scale(flip?-1:1,1);if(p.transformed){c.globalAlpha=.2+.08*Math.sin(t*9);c.fillStyle=palette.gold;c.fillRect(-20,-22,p.w+40,p.h+42);c.globalAlpha=1;for(let i=0;i<4;i++)px(c,6+i*10+Math.sin(t*4+i)*5,-18-(i%2)*8,4,18,palette.divine2);}if(p.state==='dodge'){c.globalAlpha=.35;px(c,-24,24,30,42,p.transformed?palette.gold:'#b66b63');c.globalAlpha=1;}const la=p.state==='run'?[0,5,0,-5][frame]:0,lb=-la;px(c,12+la,58,9,22,p.transformed?'#e7c45d':'#3a3a50');px(c,28+lb,58,9,22,p.transformed?'#f5df85':'#2a2b3d');px(c,9+la,77,15,5,'#17131c');px(c,25+lb,77,15,5,'#17131c');px(c,8,25,32,40,p.transformed?'#6d5521':'#ded6cf');px(c,13,28,22,34,p.transformed?'#f1d470':'#f4eee6');px(c,4,30,8,32,p.transformed?'#c69536':'#9c6f66');px(c,38,30,8,32,p.transformed?'#c69536':'#8d625d');px(c,12,4,28,23,'#e7c9b7');px(c,9,0,33,11,p.transformed?'#fff2ad':'#f3eee8');px(c,7,7,12,18,p.transformed?'#f6d66f':'#e8e2df');px(c,35,5,9,23,p.transformed?'#f7dc77':'#dad6d5');px(c,32,10,3,4,p.transformed?'#ffe460':'#6d7f95');px(c,16,21,19,5,p.transformed?'#bf8a28':'#6a4050');px(c,17,33,17,5,p.transformed?'#fff1a0':'#b4263e');const arm=p.state==='attack'||p.state==='skill'?8:0;px(c,38+arm,34,9,28,p.transformed?'#e8c657':'#d8c7bc');px(c,45+arm,17,5,52,p.transformed?'#fff4aa':'#dedfe4');px(c,49+arm,15,5,58,p.transformed?'#d8a934':'#8a5360');px(c,45+arm,12,12,6,p.transformed?'#fff7c0':'#eef0f4');if(p.hurtTimer>0){c.globalCompositeOperation='source-atop';c.fillStyle='rgba(255,40,55,.65)';c.fillRect(0,0,p.w+65,p.h);c.globalCompositeOperation='source-over';}c.restore();}
function drawEnemy(c,x,y,e){c.save();c.translate(x+(e.facing<0?e.w:0),y);c.scale(e.facing<0?-1:1,1);const f=Math.floor(e.anim*8)%2,h=e.hurt>0;if(e.type==='emberling'){px(c,7,14,29,33,h?'#ff8b7a':'#84312e');px(c,12,4,21,18,'#c94c35');px(c,17,10,5,5,'#ffd27c');px(c,24,9,5,5,'#ffd27c');px(c,8,47+f*2,9,7,'#31131a');px(c,27,47-f*2,9,7,'#31131a');px(c,34,25,13,6,'#f27a3d');}else if(e.type==='archer'){px(c,8,18,27,42,h?'#c58aa9':'#694064');px(c,11,4,24,22,'#40243f');px(c,17,11,14,5,'#e45a5e');px(c,35,22,4,37,'#d58e5b');px(c,39,20,3,42,'#f4d09a');px(c,4,58,13,6,'#21101f');px(c,26,58,13,6,'#21101f');}else if(e.type==='hound'){px(c,7,14,46,24,h?'#dc6a5d':'#65302f');px(c,43,5,18,22,'#8e3b35');px(c,53,11,5,5,'#ffbf55');px(c,4,35+f*3,12,9,'#2f151a');px(c,42,35-f*3,12,9,'#2f151a');px(c,0,17,11,6,'#d45d3a');px(c,58,1,4,8,'#d45d3a');}else{px(c,10,24,50,60,h?'#e08b6a':'#7b382d');px(c,15,4,42,32,'#a84732');px(c,22,14,27,8,'#1a0d14');px(c,26,16,7,5,'#ffc05c');px(c,39,16,7,5,'#ffc05c');px(c,0,30,15,52,'#4b2023');px(c,58,28,13,54,'#4b2023');px(c,60,12,7,78,'#d18449');px(c,66,8,10,84,'#f2ad59');if(e.shield>0){c.globalAlpha=.35;c.strokeStyle='#ffd879';c.lineWidth=6;c.strokeRect(1,0,70,91);c.globalAlpha=1;}}c.restore();}
function drawBoss(c,x,y,b){c.save();c.translate(x+(b.facing<0?b.w:0),y);c.scale(b.facing<0?-1:1,1);const pulse=.5+.5*Math.sin(b.anim*5);c.globalAlpha=.16+.12*pulse;c.fillStyle=b.phase===3?'#ff2045':'#ff5a28';c.fillRect(-24,-32,b.w+48,b.h+54);c.globalAlpha=1;px(c,18,55,78,98,b.hurt>0?'#ff8b70':'#511824');px(c,28,19,60,60,b.phase===3?'#8c1730':'#71221f');px(c,37,3,42,34,'#2c1017');px(c,24,2,16,29,'#de5e35');px(c,77,1,15,31,'#de5e35');px(c,40,31,14,8,'#ffd16c');px(c,66,31,14,8,'#ffd16c');px(c,47,48,29,7,'#1a0710');px(c,3,66,23,72,'#38101a');px(c,92,62,21,78,'#38101a');px(c,9,145,28,25,'#1b0910');px(c,80,145,29,25,'#1b0910');px(c,102,30,8,120,'#d6452a');px(c,108,18,8,138,'#ff9a4f');if(b.phase>=2)for(let i=0;i<5;i++){const a=b.anim*1.4+i*1.25;px(c,57+Math.cos(a)*65,68+Math.sin(a)*35,7,7,b.phase===3?'#ff3355':'#ffb14e');}c.restore();}
function drawPortraitPhainon(c){c.fillStyle='#1e0b18';c.fillRect(0,0,180,170);c.save();c.translate(45,7);c.scale(1.55,1.55);drawPlayer(c,0,0,{w:46,h:82,facing:1,animTime:0,state:'idle',transformed:false,hurtTimer:0});c.restore();}
function drawPortraitBoss(c){c.fillStyle='#25070c';c.fillRect(0,0,180,170);c.save();c.translate(35,-12);c.scale(1.05,1.05);drawBoss(c,0,0,{w:116,h:170,facing:1,phase:3,hurt:0,anim:1.2});c.restore();}
function drawPortraitEcho(c){c.fillStyle='#100918';c.fillRect(0,0,180,170);c.globalAlpha=.75;c.fillStyle='#8e79b5';c.beginPath();c.arc(90,68,42,0,Math.PI*2);c.fill();c.fillStyle='#d9d0ff';c.fillRect(85,54,10,28);c.fillRect(71,64,38,8);c.globalAlpha=1;}

const game=new Game();
window.__EMBERFALL_GAME__=game;
